module.exports = {
  xs: {
    'typo-heading-1': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '3.052rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '64px',
    },
    'typo-heading-2': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '2.441rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '48px',
    },
    'typo-heading-3': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.953rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '40px',
    },
    'typo-heading-4': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.563rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '32px',
    },
    'typo-subtitle': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.25rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '20px',
    },
    'typo-body-1': {
      'font-family': 'SharpGroteskMedium20',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-body-2': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-caption': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '0.8rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
  },
  sm: {
    'typo-heading-1': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '3.815rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '80px',
    },
    'typo-heading-2': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '3.052rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '64px',
    },
    'typo-heading-3': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '2.441rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '48px',
    },
    'typo-heading-4': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.563rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '32px',
    },
    'typo-subtitle': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.25rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '20px',
    },
    'typo-body-1': {
      'font-family': 'SharpGroteskMedium20',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-body-2': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-caption': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '0.8rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
  },
  md: {
    'typo-heading-1': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '4.768rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '100px',
    },
    'typo-heading-2': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '3.815rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '80px',
    },
    'typo-heading-3': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '3.052rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '64px',
    },
    'typo-heading-4': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.953rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '40px',
    },
    'typo-subtitle': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.25rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '20px',
    },
    'typo-body-1': {
      'font-family': 'SharpGroteskMedium20',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-body-2': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-caption': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '0.8rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
  },
  lg: {
    'typo-heading-1': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '5.96rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '124px',
    },
    'typo-heading-2': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '4.768rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '100px',
    },
    'typo-heading-3': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '3.815rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '80px',
    },
    'typo-heading-4': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '2.441rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '48px',
    },
    'typo-subtitle': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.25rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '20px',
    },
    'typo-body-1': {
      'font-family': 'SharpGroteskMedium20',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-body-2': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-caption': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '0.8rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
  },
  xl: {
    'typo-heading-1': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '5.96rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '124px',
    },
    'typo-heading-2': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '4.768rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '100px',
    },
    'typo-heading-3': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '3.815rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '80px',
    },
    'typo-heading-4': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '2.441rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '48px',
    },
    'typo-subtitle': {
      'font-family': 'SharpGroteskSemibold19',
      'font-size': '1.25rem',
      'font-weight': '600',
      'font-style': 'normal',
      margin: 0,
      'line-height': '20px',
    },
    'typo-body-1': {
      'font-family': 'SharpGroteskMedium20',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-body-2': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '1rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
    'typo-caption': {
      'font-family': 'SharpGroteskBook19',
      'font-size': '0.8rem',
      'font-weight': '400',
      'font-style': 'normal',
      margin: 0,
      'line-height': '16px',
    },
  },
};
