name: 'Deploy Library and Storybook'

on:
  push:
    branches:
      - main

jobs:
  install_deps:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    needs: install_deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint Projectfiles
        run: npm run lint

  build_deploy_storybook:
    name: 'Build & Deploy Storybook'
    runs-on: ubuntu-latest
    needs: [install_deps, lint]
    steps:
      - name: Checking out repository
        uses: actions/checkout@v1
      - name: Checking out node package
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Building Storybook
        run: npm run build:storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: storybook-static
